#include <d3d9.h>
#include "Imgui/imgui.h"
#include "Imgui/imgui_impl_win32.h"
#include "Imgui/imgui_impl_dx9.h"
#include "xor_enc.hpp"
#include "imported_enc.h"
#include "OptionDefine.h"
#include <dwmapi.h>
#include <thread>
#include "sdk_func.h"
#include "sdk.h"
#include "defines.h"
#include "FString.h"
#include "UE5FunctionDefines.h"
#include "MenuDefines.h"
#include <d3d10.h>
#include "HijackOverlay.h"